export const knowledgeData = [
    "Adobe Creative Suite",
    "Agile/SCRUM",
    "Angular 9",
    "Bootstrap",
    "CSS 3/SCSS",
    "Express",
    "Figma",
    "Gatsby",
    "Git/GitHub",
    "Git Kraken/Sourcetree",
    "HTML 5",
    "HubSpot",
    "JavaScript",
    "Jira",
    "JQuery",
    "JSON",
    "MongoDB/Mongoose",
    "Node",
    "React JS",
    "Responsive Web Design",
    "Sketch",
    "Storybook",
    "Zeplin",
    "PC & Macintosh Operating Systems"
  ];